/*
 * memory_maps.h
 *
 *  Created on: 2020Äê9ÔÂ6ÈÕ
 *      Author: tinglepan
 */

#ifndef SRC_INCLUDE_MEMORY_MAPS_H_
#define SRC_INCLUDE_MEMORY_MAPS_H_

#define PRESET_DATA_BASE  UINT64_C(0x60000000)
#define PRESET_DATA_MAC_OFFSET 0
#define PRESET_DATA_MEDL_OFFSET 0x10

#define PRESET_DATA_MAC_ADDR (PRESET_DATA_BASE + PRESET_DATA_MAC_OFFSET)
#define PRESET_DATA_MEDL_BASE (PRESET_DATA_BASE + PRESET_DATA_MEDL_OFFSET)

#define PRESET_DATA_SIZE 0x1000
#define PRESET_DATA_SIZE_BITS (4 + 4 + 4)

#define SHARED_REGION_BASE UINT64_C(0x60001000)
#define SHARED_REGION_VARIABLES_OFFSET 0
#define SHARED_REGION_CNI_MSG_OFFSET 0x1000
#define SHARED_REGION_TTP_TX_FRAME_OFFSET 0x2000
#define SHARED_REGION_TTP_RX_FRAME_OFFSET 0x3000

#define SHARED_REGION_ETH_TX_FRAMES_OFFSET 0x4000
#define SHARED_REGION_ETH_RX_FRAMES_OFFSET 0x5000

#define SHARED_REGION_VARIABLES_BASE (SHARED_REGION_BASE + SHARED_REGION_VARIABLES_OFFSET)
#define SHARED_REGION_CNI_MSG_BASE (SHARED_REGION_BASE + SHARED_REGION_CNI_MSG_OFFSET)
#define SHARED_REGION_TTP_TX_BASE (SHARED_REGION_BASE + SHARED_REGION_TTP_TX_FRAME_OFFSET)
#define SHARED_REGION_TTP_RX_BASE (SHARED_REGION_BASE + SHARED_REGION_TTP_RX_FRAME_OFFSET)
#define SHARED_REGION_ETH_TX_BASE (SHARED_REGION_BASE + SHARED_REGION_ETH_TX_FRAMES_OFFSET)
#define SHARED_REGION_ETH_RX_BASE (SHARED_REGION_BASE + SHARED_REGION_ETH_RX_FRAMES_OFFSET)

#define SHARED_REGION_VARIABLES_SIZE 0x1000
#define SHARED_REGION_VARIABLES_SIZE_BITS (4 + 4 + 4)
#define SHARED_REGION_CNI_MSG_SIZE 0x1000
#define SHARED_REGION_CNI_MSG_SIZE_BITS (4 + 4 + 4)
#define SHARED_REGION_TTP_SIZE 0x1000
#define SHARED_REGION_TTP_SIZE_BITS (4 + 4 + 4)
#define SHARED_REGION_ETH_SIZE 0x1000
#define SHARED_REGION_ETH_SIZE_BITS (4 + 4 + 4)

#endif /* SRC_INCLUDE_MEMORY_MAPS_H_ */
