/*
 * memory_maps.h
 *
 *  Created on: 2020Äê9ÔÂ6ÈÕ
 *      Author: tinglepan
 */

#ifndef SRC_INCLUDE_MEMORY_MAPS_H_
#define SRC_INCLUDE_MEMORY_MAPS_H_

#define PRESET_DATA_BASE 0x800000000
#define PRESET_DATA_MAC_OFFSET 0
#define PRESET_DATA_MEDL_OFFSET 0x10

#define PRESET_DATA_MAC_ADDR (PRESET_DATA_BASE + PRESET_DATA_MAC_OFFSET)
#define PRESET_DATA_MEDL_BASE (PRESET_DATA_BASE + PRESET_DATA_MEDL_OFFSET)

#define PRESET_DATA_SIZE 0x1000
#define PRESET_DATA_SIZE_BITS (4 + 4 + 4)

#define SHARED_REGION_BASE 0x810000000
#define SHARED_REGION_VARIABLES_OFFSET 0
#define SHARED_REGION_CNI_MSG_OFFSET 0x1000
#define SHARED_REGION_TTP_TX_FRAME_OFFSET 0xe000
#define SHARED_REGION_TTP_RX_FRAME_OFFSET 0xf000

#define SHARED_REGION_ETH_TX_FRAMES_OFFSET 0x10000
#define SHARED_REGION_ETH_RX_FRAMES_OFFSET 0x20000

#define SHARED_REGION_VARIABLES_BASE (SHARED_REGION_BASE + SHARED_REGION_VARIABLES_OFFSET)
#define SHARED_REGION_CNI_MSG_BASE (SHARED_REGION_BASE + SHARED_REGION_CNI_MSG_OFFSET)
#define SHARED_REGION_TTP_TX_BASE (SHARED_REGION_BASE + SHARED_REGION_TTP_TX_FRAME_OFFSET)
#define SHARED_REGION_TTP_RX_BASE (SHARED_REGION_BASE + SHARED_REGION_TTP_RX_FRAME_OFFSET)
#define SHARED_REGION_ETH_TX_BASE (SHARED_REGION_BASE + SHARED_REGION_ETH_TX_FRAMES_OFFSET)
#define SHARED_REGION_ETH_RX_BASE (SHARED_REGION_BASE + SHARED_REGION_ETH_RX_FRAMES_OFFSET)

#define SHARED_REGION_VARIABELS_SIZE 0x1000
#define SHARED_REGION_VARIABELS_SIZE_BITS (4 + 4 + 4)
#define SHARED_REGION_CNI_MSG_SIZE 0x8000
#define SHARED_REGION_CNI_MSG_SIZE_BITS (4 + 4 + 4 + 3)
#define SHARED_REGION_TTP_SIZE 0x1000
#define SHARED_REGION_TTP_SIZE_BITS (4 + 4 + 4)
#define SHARED_REGION_ETH_SIZE 0x10000
#define SHARED_REGION_ETH_SIZE_BITS (4 + 4 + 4 + 4)

#endif /* SRC_INCLUDE_MEMORY_MAPS_H_ */
